# BEGIN_KITTY_THEME
# Kibble
include current-theme.conf
# END_KITTY_THEME

# Fonts (M)
# font_family      Operator Mono Medium
# bold_font        Operator Mono Book
# italic_font      Operator Mono Medium Italic
# bold_italic_font Operator Mono Book Italic
# font_family      JetBrains Mono NL
# bold_font        JetBrains Mono NL ExtraBold
# bold_italic_font JetBrains Mono NL ExtraBold Italic
font_family      JetBrains Mono 
bold_font        JetBrains Mono ExtraBold
bold_italic_font JetBrains Mono ExtraBold Italic

# AV
enable_audio_bell no
tab_bar_edge top
tab_bar_style powerline

# Pasting stuff (remove paternalism)
paste_actions no-op

# Keyboard shortcuts
map ctrl+shift+t new_tab_with_cwd
map ctrl+alt+n next_tab
map ctrl+alt+p previous_tab

# enabled_layouts tall
# map ctrl+shift+d launch --cwd=current
enabled_layouts splits
# Vertical split
map ctrl+shift+a>ctrl+shift+/ launch --cwd=last_reported --location=vsplit
# Horizontal split
map ctrl+shift+a>ctrl+shift+- launch --cwd=last_reported --location=hsplit
# Split home
map ctrl+shift+a>ctrl+shift+h launch --cwd=~ --location=vsplit


# vim-like window motions
map ctrl+shift+h neighboring_window left
map ctrl+shift+l neighboring_window right
map ctrl+shift+k neighboring_window up
map ctrl+shift+j neighboring_window down

map ctrl+alt+u kitten unicode_input


# Make urls ctrl+shift+click
mouse_map left click ungrabbed no_op

# Background
# background_image /home/jonathan/Pictures/charizard.png
# background_image /home/jonathan/Pictures/thugJC.png
background_image /home/jonathan/Pictures/thugReformed.png
background_image_layout centered
background_tint 0.9

# background_image /home/jonathan/Pictures/JamesFunky.png
# background_tint 0.7

# background from theme
wayland_titlebar_color #0e100a


# Force shift+enter through for claude code
map shift+enter send_text all \x1b[13;2u
